### PR TITLE
Updated upstream repo .

### PR DESCRIPTION
**Pull request by ronin08**

### CODE REVIEW

**Comment by anasty17** [comment]
🙄🙄

**Comment by ronin08** [comment]
> 🙄🙄

yeah .. weird little change and it not even affrect the deploy ... but whatsoever I submitted :)

**Comment by guptaofficial17** [comment]
why whenever i try to upload bot on heroku its get suspended

**Comment by Appucodex** [comment]
Are use latest repo

**Comment by guptaofficial17** [comment]
working fine now

**Pull request merged**
